const line = (text: string) => text;

const buildScript = (origin: string) => [
  '#!/usr/bin/env bash',
  'set -euo pipefail',
  'SERVER_ID="${1:-}"',
  'TOKEN="${2:-}"',
  `APP_URL="${origin}"`,
  'if [ -z "$SERVER_ID" ] || [ -z "$TOKEN" ]; then',
  '  echo "Usage: install <server_id> <token>" >&2',
  '  exit 1',
  'fi',
  'mkdir -p /opt/its-syncera',
  "cat >/opt/its-syncera/agent.sh <<'AGENT'",
  '#!/usr/bin/env bash',
  'set -euo pipefail',
  'SERVER_ID="__SERVER_ID__"',
  'TOKEN="__TOKEN__"',
  'APP_URL="__APP_URL__"',
  line("CPU=$(awk '/cpu /{u=$2+$4; t=$2+$4+$5; if (t>0) printf \"%.0f\", (u/t)*100; else print 0}' /proc/stat)"),
  line("MEM=$(free | awk '/Mem:/{if ($2>0) printf \"%.0f\", ($3/$2)*100; else print 0}')"),
  line("DISK=$(df -P / | awk 'NR==2{gsub(/%/,\"\",$5); print $5}')"),
  'OS=$(if [ -r /etc/os-release ]; then . /etc/os-release; echo "${PRETTY_NAME:-Linux}"; else uname -s; fi)',
  'UPTIME=$(uptime -p 2>/dev/null || uptime)',
  line("NET=$(awk 'NR>2{rx+=$2; tx+=$10} END{printf \"rx %.1fMB tx %.1fMB\", rx/1048576, tx/1048576}' /proc/net/dev)"),
  'SERVICES="[]"',
  'if command -v systemctl >/dev/null 2>&1; then',
  "  SERVICES=$(systemctl list-units --type=service --state=running --no-legend 2>/dev/null | head -8 | python3 -c 'import json,sys; print(json.dumps([{\"name\":l.split()[0],\"status\":\"online\",\"response\":\"running\"} for l in sys.stdin if l.strip()]))' 2>/dev/null || echo '[]')",
  'fi',
  'export SERVER_ID TOKEN APP_URL CPU MEM DISK OS UPTIME NET SERVICES',
  "python3 - <<'PY'",
  'import json, os, urllib.request',
  'payload={',
  "  'serverId':os.environ.get('SERVER_ID'),",
  "  'token':os.environ.get('TOKEN'),",
  "  'os':os.environ.get('OS'),",
  "  'cpuUsage':float(os.environ.get('CPU') or 0),",
  "  'memoryUsage':float(os.environ.get('MEM') or 0),",
  "  'storageUsage':float(os.environ.get('DISK') or 0),",
  "  'uptime':os.environ.get('UPTIME'),",
  "  'networkTraffic':os.environ.get('NET'),",
  "  'services':json.loads(os.environ.get('SERVICES') or '[]'),",
  '}',
  "req=urllib.request.Request(os.environ.get('APP_URL') + '/api/agent/heartbeat', data=json.dumps(payload).encode(), method='POST', headers={'Content-Type':'application/json'})",
  'with urllib.request.urlopen(req, timeout=20) as r:',
  '  print(r.read().decode())',
  'PY',
  'AGENT',
  'python3 - <<PY',
  'from pathlib import Path',
  'p=Path("/opt/its-syncera/agent.sh")',
  's=p.read_text()',
  's=s.replace("__SERVER_ID__", """${SERVER_ID}""").replace("__TOKEN__", """${TOKEN}""").replace("__APP_URL__", """${APP_URL}""")',
  'p.write_text(s)',
  'PY',
  'chmod +x /opt/its-syncera/agent.sh',
  'if command -v systemctl >/dev/null 2>&1; then',
  "  cat >/etc/systemd/system/its-syncera-agent.service <<'EOF'",
  '[Unit]',
  'Description=ItsSyncera Agent',
  'After=network-online.target',
  '',
  '[Service]',
  'Type=oneshot',
  'ExecStart=/opt/its-syncera/agent.sh',
  'EOF',
  "  cat >/etc/systemd/system/its-syncera-agent.timer <<'EOF'",
  '[Unit]',
  'Description=Run ItsSyncera Agent every minute',
  '',
  '[Timer]',
  'OnBootSec=30',
  'OnUnitActiveSec=60',
  'Unit=its-syncera-agent.service',
  '',
  '[Install]',
  'WantedBy=timers.target',
  'EOF',
  '  systemctl daemon-reload',
  '  systemctl enable --now its-syncera-agent.timer',
  'fi',
  '/opt/its-syncera/agent.sh',
  '',
].join('\n');

export default function handler(req: any, res: any) {
  const proto = String(req.headers?.['x-forwarded-proto'] || 'https').split(',')[0];
  const host = req.headers?.host || 'its-syncera.vercel.app';
  res.setHeader('Content-Type', 'text/plain; charset=utf-8');
  res.status(200).send(buildScript(`${proto}://${host}`));
}
